#!/usr/bin/env bash
# =============================================================================
# AI Codebase Audit — Schema Connectivity & Integration Gap Scanner
# Md. Sowad Al-Mughni | https://github.com/sowadalmughni/ai-codebase-audit
#
# USAGE:  bash scripts/scan-schema.sh [root-dir]
# DETECTS: Tables created in migrations but never queried in application code,
#          ORM models not referenced in services, hardcoded mocks in production paths
# =============================================================================

ROOT="${1:-.}"
EXCLUDE="--exclude-dir=node_modules --exclude-dir=.git --exclude-dir=dist --exclude-dir=build --exclude-dir=.next --exclude-dir=__pycache__"
FINDINGS=0

echo ""
echo "═══════════════════════════════════════════════════"
echo "  SCHEMA CONNECTIVITY SCAN — HIGH"
echo "  $(date)"
echo "═══════════════════════════════════════════════════"
echo ""

# ─────────────────────────────────────────────────────
# 1. Extract table names from migration files
# ─────────────────────────────────────────────────────
MIGRATION_TABLES=()
MIGRATION_DIRS=$(find "$ROOT" -type d \( -name "migrations" -o -name "migration" \) 2>/dev/null | grep -v "node_modules\|\.git\|dist\|build")

if [ -n "$MIGRATION_DIRS" ]; then
  echo "── Extracting tables from migrations ────────────"
  for dir in $MIGRATION_DIRS; do
    while IFS= read -r table; do
      [ -n "$table" ] && MIGRATION_TABLES+=("$table")
    done < <(grep -rhoP "(?i)CREATE TABLE (IF NOT EXISTS )?['\`]?\K[a-zA-Z_][a-zA-Z0-9_]*" "$dir" 2>/dev/null | sort -u)
  done
  echo "  Found ${#MIGRATION_TABLES[@]} table(s) in migrations: ${MIGRATION_TABLES[*]}"
fi

# Also check Prisma schema
PRISMA_SCHEMA=$(find "$ROOT" -name "schema.prisma" 2>/dev/null | head -1)
if [ -n "$PRISMA_SCHEMA" ]; then
  echo ""
  echo "── Extracting models from Prisma schema ─────────"
  while IFS= read -r model; do
    [ -n "$model" ] && MIGRATION_TABLES+=("${model,,}")  # lowercase
  done < <(grep -oP "^model \K[A-Za-z]+" "$PRISMA_SCHEMA" 2>/dev/null)
  echo "  Found ${#MIGRATION_TABLES[@]} total model(s)"
fi

# ─────────────────────────────────────────────────────
# 2. Check each table for application references
# ─────────────────────────────────────────────────────
echo ""
echo "── Checking table/model references in application code ──"

for table in "${MIGRATION_TABLES[@]}"; do
  # Skip common system tables
  [[ "$table" =~ ^(schema_migrations|knex_migrations|_prisma_migrations|spatial_ref_sys|alembic_version)$ ]] && continue

  # Look for the table name in application code (excluding migrations themselves)
  REFS=$(grep -rln "\b${table}\b" "$ROOT" $EXCLUDE \
    --include="*.ts" --include="*.tsx" --include="*.js" --include="*.py" \
    2>/dev/null | grep -Ev "migration|seed|test|spec" | head -5)

  if [ -z "$REFS" ]; then
    echo ""
    echo "  ⚠  HIGH — Table '$table' never referenced in application code"
    echo "     Created in migrations but no service, repository, or query uses it"
    echo ""
    echo "  FIX OPTIONS:"
    echo "    a) Wire it: create a repository and service for '$table'"
    echo "    b) Delete it: if this table was generated by mistake and is not needed"
    echo "    c) Defer it: if it's planned but not yet implemented, mark it clearly"
    FINDINGS=$((FINDINGS + 1))
  else
    echo "  ✓ '$table' referenced in: $(echo "$REFS" | tr '\n' ' ')"
  fi
done

# ─────────────────────────────────────────────────────
# 3. Find hardcoded mock data in non-test files
# ─────────────────────────────────────────────────────
echo ""
echo "── Scanning for hardcoded mock data in production paths ──"

MOCK_HITS=$(grep -rPn "const (mock|fake|dummy|stub|placeholder)[A-Z_]|// ?mock data|# ?mock data" \
  "$ROOT" $EXCLUDE \
  --include="*.ts" --include="*.tsx" --include="*.js" --include="*.py" \
  2>/dev/null | grep -Ev "test|spec|__tests__|\.test\.|\.spec\." | head -20)

if [ -n "$MOCK_HITS" ]; then
  echo ""
  echo "  ⚠  HIGH — Hardcoded mock data outside test files"
  echo "$MOCK_HITS" | while IFS= read -r line; do
    echo "      $line"
  done
  echo ""
  echo "  FIX: Replace mock data with real API calls or database queries."
  echo "  Each occurrence above should be traced to its data source."
  FINDINGS=$((FINDINGS + 1))
else
  echo "  ✓ No hardcoded mock data found outside test files"
fi

# ─────────────────────────────────────────────────────
# 4. Find integration TODO comments
# ─────────────────────────────────────────────────────
echo ""
echo "── Scanning for integration gap TODO comments ───"

INTEGRATION_TODOS=$(grep -rPn "TODO.{0,60}(api|backend|database|db|fetch|connect|wire|integrate|supabase|prisma|mongoose|orm|endpoint)" \
  "$ROOT" $EXCLUDE \
  --include="*.ts" --include="*.tsx" --include="*.js" --include="*.py" \
  2>/dev/null | grep -Ev "node_modules" | head -30)

if [ -n "$INTEGRATION_TODOS" ]; then
  TODO_COUNT=$(echo "$INTEGRATION_TODOS" | wc -l)
  echo ""
  echo "  ⚠  HIGH — $TODO_COUNT integration gap(s) marked with TODO"
  echo "$INTEGRATION_TODOS" | while IFS= read -r line; do
    echo "      $line"
  done
  echo ""
  echo "  Each TODO above represents an unfinished integration."
  echo "  These should each have an Architecture Spec entry and an implementation task."
  FINDINGS=$((FINDINGS + 1))
else
  echo "  ✓ No integration gap TODO comments found"
fi

# ─────────────────────────────────────────────────────
# 5. Find placeholder/stub function bodies
# ─────────────────────────────────────────────────────
echo ""
echo "── Scanning for placeholder function bodies ─────"

STUBS=$(grep -rPn "return \[\]|return \{\}|return null|return None|pass$|raise NotImplementedError|throw new Error\(['\"]not implemented" \
  "$ROOT" $EXCLUDE \
  --include="*.ts" --include="*.js" --include="*.py" \
  2>/dev/null | grep -Ev "test|spec|__tests__|interface|abstract|declare" | head -20)

if [ -n "$STUBS" ]; then
  STUB_COUNT=$(echo "$STUBS" | wc -l)
  echo ""
  echo "  ⚠  MEDIUM — $STUB_COUNT potential stub/placeholder function(s)"
  echo "$STUBS" | while IFS= read -r line; do
    echo "      $line"
  done
  echo ""
  echo "  Review each: if this is production code that should return real data,"
  echo "  it represents an unfinished integration."
  FINDINGS=$((FINDINGS + 1))
else
  echo "  ✓ No obvious stub function bodies found"
fi

# ─────────────────────────────────────────────────────
# SUMMARY
# ─────────────────────────────────────────────────────
echo ""
echo "═══════════════════════════════════════════════════"
echo "  Schema scan complete — $FINDINGS finding category(ies)"
echo "  Add confirmed gaps to: templates/remediation-register.md"
echo "═══════════════════════════════════════════════════"
echo ""
